apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-reddit-app
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app.kubernetes.io/instance: reddit-app
spec:
  ingressClassName: alb  # Essential for AWS ALB
  rules:
    - http:  # Removed 'host' so it works with the ELB URL directly
        paths:
          - path: /  # Changed from /test to /
            pathType: Prefix
            backend:
              service:
                name: reddit-clone-service
                port:
                  number: 3000